config/routes.rb
Myblog::Application.routes.draw do
  root to: 'articles#index'
  resources :users
  resources :articles
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'
  resources :categories
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  attr_accessible :title, :desc, :user_id, :category_ids
  validates :title, presence: true, length: { minimum: 3, maximum: 30 }
  validates :desc, presence: true, length: { minimum: 6, maximum: 5000 }
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { maximum: 30, minimum: 3 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  attr_accessible :email, :username, :password, :role

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: EMAIL_REGEX }

  validates :username, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { minimum: 3, maximum: 25 }

  before_save { self.email = email.downcase }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # makes methods to be used in both views & other controllers
  helper_method :current_user, :signed_in?, :article_count, :category_count

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def signed_in?
    !!current_user
  end

  def article_count
    Article.count
  end

  def category_count
    Category.count
  end

  # cannot be used in views
  def require_user
    if !signed_in?
      flash[:alert] = 'You must be logged in'
      redirect_to signin_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :set_article, only: %i[show edit update destroy]
  before_filter :require_user, except: %i[new show index]
  before_filter :require_correct_user, only: %i[edit update destroy]

  def index
    @articles = Article.page(params[:page]).per(3)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params[:article])
    @article.user_id = current_user.id

    if @article.save
      flash[:notice] = 'Article created successfully'
      redirect_to @article
    else
      flash[:notice] = 'Article creation failed'
      redirect_to current_user
    end
  end

  def edit; end

  def show; end

  def update
    if @article.update_attributes(params[:article])
      flash[:notice] = "Article #{@article.id} updated successfully"
    else
      flash[:notice] = "Article #{@article.id} update failed"
    end
    redirect_to @article
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article #{@article.id} deleted successfully"
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def require_correct_user
    if current_user != @article.user
      flash[:alert] = 'You are not authorized'
      redirect_to current_user
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :require_admin, except: %i[show index]

  def index
    @categories = Category.page(params[:page]).per(5)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.page(params[:page]).per(3)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      flash[:notice] = 'Category created successfully'
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      flash[:notice] = 'Category updated successfully'
    else
      flash[:alert] = 'Category update failed'
    end
    redirect_to @category
  end

  private

  def require_admin
    unless signed_in? && current_user.role > 1
      flash[:alert] = 'Only admins are allowed'
      redirect_to categories_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    puts params
    user = User.where(email: params[:session][:email].downcase).first
    if user
      if user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:notice] = 'SignIn successful'
        redirect_to user
      else
        puts "password mismatch"
        flash[:alert] = "Invalid Sign In details"
        redirect_to signin_path
      end
    else
      flash[:alert] = "Account not found"
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Sign Out successful'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :require_user, except: [:new, :create, :show]
  before_filter :require_correct_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      flash['notice'] = 'Sign Up successful'
      redirect_to @user
    else
      render 'new'
    end
  end

  def index
  end

  def show
  end

  def edit
  end


  def update
    if @user.update_attributes(params[:user])
      flash['notice'] = 'Update successful'
      redirect_to @user
    end
  end

  def destroy
    if @user.destroy
      session[:user_id] = nil
      flash['notice'] = 'Account deleted successfully'
      redirect_to root_path
    else
      flash['notice'] = 'Unable to delete account'
      redirect_to @user
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def require_correct_user
    if current_user != @user
      flash[:alert] = "You are not authorized"
      redirect_to current_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
  end

end

app/views/articles/_newarticleform.html.erb
<div class="card mt-3 ms-3" style="width: 50rem;">
  <div class="card-body p-3">
    <%= form_for @article do |article| %>
      <div class="mb-3">
        <%= article.label :title, "Article Title", class: "form-label" %>
        <%= article.text_field :title, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= article.label :desc, "Article Description", class: "form-label" %>
        <%= article.text_area :desc, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= article.label :category_ids, "Select Categories", class: "form-label" %>
        <%= article.collection_select(:category_ids, Category.all, :id, :name,
                                      { prompt: true },{ multiple: true, size: 5, class: 'custom-select form-control' }) %>
      </div>

      <%= article.submit(class:"btn btn-primary") %>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<%= render 'common/titlecard', title: 'Edit Article', subtitle: 'update article details' %>
<%= render 'common/errors', obj: @article %>
<%= render 'newarticleform' %>

app/views/articles/index.html.erb
<%= render 'common/titlecard', title: 'Articles', subtitle: "total #{article_count} articles" %>

<div class="digg_pagination position-relative top-0 start-50 translate-middle mt-3", style="width: 50rem;">
  <%= paginate @articles %>
</div>

<%= render 'common/miniarticles', articles: @articles %>

app/views/articles/new.html.erb
<%= render 'common/titlecard', title: 'New Article', subtitle: 'create new article' %>
<%= render 'common/errors', obj: @article %>
<%= render 'newarticleform' %>

app/views/articles/show.html.erb
<%= render 'common/titlecard', title: '', subtitle: "Updated #{time_ago_in_words(@article.updated_at)}" %>

<div class="card mt-3 ms-3" style="width: 50rem;">
  <div class="card-header">
      <%= @article.title %>
      <% if signed_in? && current_user == @article.user %>
      <a class="position-absolute top-2 end-0 me-2 dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">More</a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><%= link_to "Edit", edit_article_path(@article), class: "dropdown-item" %></li>
          <li><%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %></li>
        </ul>
      <% end %>
  </div>
  
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><%= @article.desc %></p>
      <footer class="blockquote-footer">written by <cite title="Author"><%= @article.user.username %></cite></footer>
    </blockquote>
  </div>
</div>


<%= render @article.categories %>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class:"badge rounded-pill bg-primary ms-2 mt-3" %>

app/views/categories/_newcategoryform.html.erb
<div class="card mt-3 ms-3" style="width: 50rem;">
  <div class="card-body p-3">
    <%= form_for @category do |category| %>
      <div class="mb-3">
        <%= category.label :name, "Category Name", class: "form-label" %>
        <%= category.text_field :name, class: "form-control" %>
      </div>

      <%= category.submit class:"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<%= render 'common/titlecard', title: 'Edit Category', subtitle: 'update category name' %>
<%= render 'common/errors', obj: @category %>
<%= render 'newcategoryform' %>

app/views/categories/index.html.erb
<%= render 'common/titlecard', title: 'Categories', subtitle: "total #{category_count} articles" %>
<div class="digg_pagination position-relative top-0 start-50 translate-middle mt-3", style="width: 50rem;">
  <%= paginate @categories %>
</div>
<%= render 'common/mini-categories' %>

app/views/categories/new.html.erb
<%= render 'common/titlecard', title: 'New Category', subtitle: 'create new category' %>
<%= render 'common/errors', obj: @category %>
<%= render 'newcategoryform' %>

app/views/categories/show.html.erb
<%= render 'common/titlecard', title: @category.name, subtitle: "Created #{time_ago_in_words(@category.created_at)}" %>
<%= link_to 'Edit', edit_category_path(@category), class:"badge rounded-pill bg-danger ms-4 mt-2" %>


<div class="digg_pagination position-relative top-0 start-50 translate-middle mt-3", style="width: 50rem;">
  <%= paginate @articles %>
</div>
<%= render 'common/miniarticles', articles: @articles %>

app/views/common/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show ms-3 mt-3 me-3 mb-3" role="alert">
    <h5 class="alert-heading">Operation failed because of below errors</h5>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <hr>
    <ul> 
      <% obj.errors.full_messages.each do |msg| %>
        <li class="mb-0"><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/common/_flashmessages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert <%= name == :alert ? 'alert-danger' : 'alert-success' %> alert-dismissible fade show " role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/common/_mini-categories.html.erb
<% @categories.each do |category| %>
  <div class="card ms-3 mt-3" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= link_to category.name, category_path(category) %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= pluralize(category.articles.count, 'Article') %></h6>
    </div>
  </div>
<% end %>

app/views/common/_miniarticles.html.erb
<% articles.each do |article| %>
  <div class="card mt-3 ms-3" style="width: 50rem;">
    
    <div class="card-header">
        <%= article.title %>
        <a class="position-absolute top-2 end-0 me-2 dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">More</a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><%= link_to "View", article_path(article), class: "dropdown-item" %></li>
          <% if signed_in? && current_user == article.user %>
            <li><%= link_to "Edit", edit_article_path(article), class: "dropdown-item" %></li>
            <li><%= link_to "Delete", article_path(article), method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %></li>
          <% end %>
        </ul>
    </div>
    
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p><%= article.desc[0..150] %></p>
        <footer class="blockquote-footer">written by <cite title="Author"><%= article.user.username %></cite></footer>
      </blockquote>
    </div>

    <div class='container mb-4'>
        <%= render article.categories %>
    </div>
  </div>
<% end %>

app/views/common/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "MyBlog", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <% unless signed_in? %>
          <li class="nav-item">
            <%= link_to "Sign In", signin_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", signup_path, class:"nav-link" %>
          </li>
        <% end %>
        <% if signed_in? %>
          <li class="nav-item">
            <%= link_to "New Article", new_article_path, class:"nav-link" %>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "View Categories", categories_path, class: "dropdown-item" %></li>
              <% if signed_in? && current_user.role > 1 %>
                <li><%= link_to "New Category", new_category_path, class: "dropdown-item" %></li>
              <% end %>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.username %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %></li>
              <li><%= link_to "Delete Account", user_path(current_user), method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %></li>
              <li><%= link_to "Sign Out", signout_path, method: 'delete', class:"dropdown-item" %></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/common/_titlecard.html.erb
<div class="card ms-3 mt-3" style="width: 18rem;">
  <%= image_tag(image, class:"card-img-top") if defined?(image) %>
  <div class="card-body">
    <h5 class="card-title"><%= title %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= subtitle %></h6>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myblog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
<%= render 'common/nav' %>
<%= render 'common/flashmessages' %>
<%= yield %>

</body>
</html>

app/views/users/_signupform.html.erb
<div class="card mt-3 ms-3" style="width: 50rem;">
  <div class="card-body p-3">
    <%= form_for @user do |user| %>
      <div class="mb-3">
        <%= user.label :email, "Email Address", class: "form-label" %>
        <%= user.email_field :email, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= user.label :username, class: "form-label" %>
        <%= user.text_field :username, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= user.label :password, class: "form-label" %>
        <%= user.password_field :password, class: "form-control" %>
      </div>

      <%= user.submit(@user.new_record? ? 'Sign Up' : 'Edit Profile', class:"btn btn-primary")%>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'common/titlecard', title: 'Edit Profile', subtitle: 'edit account details' %>
<%= render 'common/errors', obj: @user %>
<%= render 'signupform' %>

app/views/users/index.html.erb
<%= render 'common/titlecard', title: 'User Details', subtitle: 'create on 12th june' %>

app/views/users/new.html.erb
<%= render 'common/titlecard', title: 'Sign Up', subtitle: 'create new account' %>
<%= render 'common/errors', obj: @user %>
<%= render 'signupform' %>

app/views/users/show.html.erb
<%= render 'common/titlecard', image: gravatar_for(@user, { size: 200 }), title: @user.username, subtitle: "Joined #{time_ago_in_words(@user.created_at)}" %>
<%= render 'common/miniarticles', articles: @user.articles %>